"""Normalized Ascend onboarding question bank."""

from __future__ import annotations

from typing import Any

ONBOARDING_QUESTION_BANK: list[dict[str, Any]] = [
    {
        "id": 1,
        "code": "ob_01",
        "category": "PHYSICAL",
        "readiness_component": "Physical Readiness",
        "question": "How would you rate your current physical conditioning?",
        "description": "Choose the response that fits you best. Your answers build a starting baseline.",
        "answer_type": "single_select",
        "scoreable": True,
        "reverse_scored": False,
        "options": ["Below standard", "Building", "Ready", "Peak"],
        "routing_text": "Support is available. This answer routes to your PT/IM provider for review.",
        "routing_trigger": ["Below standard"],
        "provider_route": "PT/IM",
        "ai_tags": ["physical", "baseline", "provider-review"],
    },
    {
        "id": 2,
        "code": "ob_02",
        "category": "PHYSICAL",
        "readiness_component": "Physical Readiness",
        "question": "How often do you meet the physical activity baseline each week?",
        "description": "Choose the response that fits you best. Your answers build a starting baseline.",
        "answer_type": "single_select",
        "scoreable": True,
        "reverse_scored": False,
        "options": ["Never", "Rarely", "Most weeks", "Every week"],
        "routing_text": "Support is available. This answer routes to your PT/IM provider for review.",
        "routing_trigger": ["Never", "Rarely"],
        "provider_route": "PT/IM",
        "ai_tags": ["physical", "baseline", "provider-review"],
    },
    {
        "id": 3,
        "code": "ob_03",
        "category": "PHYSICAL",
        "readiness_component": "Physical Readiness",
        "question": "Are you currently managing any pain, injury, or limitation?",
        "description": "This sets context for your providers. Your choice opens a short follow-up.",
        "answer_type": "single_select",
        "scoreable": False,
        "reverse_scored": False,
        "options": ["No", "Yes - minor", "Yes - moderate", "Yes - significant"],
        "routing_text": "Routes to PT/IM review. Your answer fires a PT/IM review work item. It does NOT contribute to your OPS score.",
        "routing_trigger": ["Yes - minor", "Yes - moderate", "Yes - significant"],
        "provider_route": "PT/IM",
        "follow_up": {
            "type": "severity_sheet",
            "title": "How much is it affecting you?",
            "required_when_triggered": True,
            "save_label": "Save follow-up",
            "trigger_options": ["Yes - minor", "Yes - moderate", "Yes - significant"],
            "options": [
                {"label": "Minor", "description": "I can continue normal activity."},
                {"label": "Moderate", "description": "I need an adjustment or support."},
                {"label": "Significant", "description": "It is limiting normal activity."},
            ],
        },
        "ai_tags": ["physical", "flag-only", "ptim-review"],
    },
    {
        "id": 4,
        "code": "ob_04",
        "category": "NUTRITIONAL",
        "readiness_component": "Nutritional Readiness",
        "question": "How balanced are your meals on a typical day?",
        "description": "Choose the response that fits you best. Your answers build a starting baseline.",
        "answer_type": "single_select",
        "scoreable": True,
        "reverse_scored": False,
        "options": ["Mostly skipped", "Inconsistent", "Mostly balanced", "Fully balanced"],
        "routing_text": "Support is available. This answer routes to your PT/IM provider for review.",
        "routing_trigger": ["Mostly skipped", "Inconsistent"],
        "provider_route": "PT/IM",
        "ai_tags": ["nutrition", "baseline", "provider-review"],
    },
    {
        "id": 5,
        "code": "ob_05",
        "category": "NUTRITIONAL",
        "readiness_component": "Nutritional Readiness",
        "question": "How well do you stay hydrated during duty hours?",
        "description": "Choose the response that fits you best. Your answers build a starting baseline.",
        "answer_type": "single_select",
        "scoreable": True,
        "reverse_scored": False,
        "options": ["Rarely", "Sometimes", "Usually", "Always"],
        "routing_text": "Support is available. This answer routes to your PT/IM provider for review.",
        "routing_trigger": ["Rarely", "Sometimes"],
        "provider_route": "PT/IM",
        "ai_tags": ["nutrition", "baseline", "provider-review"],
    },
    {
        "id": 6,
        "code": "ob_06",
        "category": "NUTRITIONAL",
        "readiness_component": "Nutritional Readiness",
        "question": "How often do you rely on supplements or fueling during high demand?",
        "description": "Choose the response that fits you best. Your answers build a starting baseline.",
        "answer_type": "single_select",
        "scoreable": True,
        "reverse_scored": False,
        "options": ["Never", "Occasionally", "Often", "Every shift"],
        "routing_text": "Support is available. This answer routes to your PT/IM provider for review.",
        "routing_trigger": ["Often", "Every shift"],
        "provider_route": "PT/IM",
        "ai_tags": ["nutrition", "baseline", "provider-review"],
    },
    {
        "id": 7,
        "code": "ob_07",
        "category": "MENTAL",
        "readiness_component": "Mental Readiness",
        "question": "How well are you able to focus during demanding tasks?",
        "description": "Choose the response that fits you best. Your answers build a starting baseline.",
        "answer_type": "single_select",
        "scoreable": True,
        "reverse_scored": False,
        "options": ["Easily distracted", "Variable", "Focused", "Locked in"],
        "routing_text": "Support is available. This answer routes to your PT/IM provider for review.",
        "routing_trigger": ["Easily distracted"],
        "provider_route": "PT/IM",
        "ai_tags": ["mental", "baseline", "provider-review"],
    },
    {
        "id": 8,
        "code": "ob_08",
        "category": "MENTAL",
        "readiness_component": "Mental Readiness",
        "question": "How would you rate your current stress load?",
        "description": "Choose the response that fits you best. Your answers build a starting baseline.",
        "answer_type": "single_select",
        "scoreable": True,
        "reverse_scored": False,
        "options": ["Overwhelmed", "Stretched", "Manageable", "Calm"],
        "routing_text": "Support is available. This answer routes to your PT/IM provider for review.",
        "routing_trigger": ["Overwhelmed", "Stretched"],
        "provider_route": "PT/IM",
        "ai_tags": ["mental", "baseline", "provider-review"],
    },
    {
        "id": 9,
        "code": "ob_09",
        "category": "MENTAL",
        "readiness_component": "Mental Readiness",
        "question": "How confident do you feel about your next mission or task?",
        "description": "Choose the response that fits you best. Your answers build a starting baseline.",
        "answer_type": "single_select",
        "scoreable": True,
        "reverse_scored": False,
        "options": ["Not confident", "Hesitant", "Mostly sure", "Highly confident"],
        "routing_text": "Support is available. This answer routes to your PT/IM provider for review.",
        "routing_trigger": ["Not confident", "Hesitant"],
        "provider_route": "PT/IM",
        "ai_tags": ["mental", "baseline", "provider-review"],
    },
    {
        "id": 10,
        "code": "ob_10",
        "category": "SPIRITUAL",
        "readiness_component": "Spiritual Readiness",
        "question": "How connected do you feel to your sense of purpose right now?",
        "description": "Choose the response that fits you best. Your answers build a starting baseline.",
        "answer_type": "single_select",
        "scoreable": True,
        "reverse_scored": False,
        "options": ["Disconnected", "Searching", "Grounded", "Deeply rooted"],
        "routing_text": "Support is available. This answer routes to your PT/IM provider for review.",
        "routing_trigger": ["Disconnected"],
        "provider_route": "PT/IM",
        "ai_tags": ["spiritual", "baseline", "provider-review"],
    },
    {
        "id": 11,
        "code": "ob_11",
        "category": "SPIRITUAL",
        "readiness_component": "Spiritual Readiness",
        "question": "How often do you engage in reflection, prayer, or values-based practice?",
        "description": "Choose the response that fits you best. Your answers build a starting baseline.",
        "answer_type": "single_select",
        "scoreable": True,
        "reverse_scored": False,
        "options": ["Rarely", "Sometimes", "Weekly", "Daily"],
        "routing_text": "Support is available. This answer routes to your PT/IM provider for review.",
        "routing_trigger": ["Rarely"],
        "provider_route": "PT/IM",
        "ai_tags": ["spiritual", "baseline", "provider-review"],
    },
    {
        "id": 12,
        "code": "ob_12",
        "category": "SPIRITUAL",
        "readiness_component": "Spiritual Readiness",
        "question": "How supported do you feel by your community or unit?",
        "description": "Choose the response that fits you best. Your answers build a starting baseline.",
        "answer_type": "single_select",
        "scoreable": True,
        "reverse_scored": False,
        "options": ["Isolated", "Loose ties", "Connected", "Strongly supported"],
        "routing_text": "Support is available. This answer routes to your PT/IM provider for review.",
        "routing_trigger": ["Isolated"],
        "provider_route": "PT/IM",
        "ai_tags": ["spiritual", "baseline", "provider-review"],
    },
    {
        "id": 13,
        "code": "ob_13",
        "category": "SLEEP",
        "readiness_component": "Sleep Readiness",
        "question": "How many hours of sleep do you get on a typical night?",
        "description": "Choose the response that fits you best. Your answers build a starting baseline.",
        "answer_type": "single_select",
        "scoreable": True,
        "reverse_scored": False,
        "options": ["Less than 4", "4 to 6", "6 to 7", "7 or more"],
        "routing_text": "Support is available. This answer routes to your PT/IM provider for review.",
        "routing_trigger": ["Less than 4", "4 to 6"],
        "provider_route": "PT/IM",
        "ai_tags": ["sleep", "baseline", "provider-review"],
    },
    {
        "id": 14,
        "code": "ob_14",
        "category": "SLEEP",
        "readiness_component": "Sleep Readiness",
        "question": "How restful is your sleep when you do sleep?",
        "description": "Choose the response that fits you best. Your answers build a starting baseline.",
        "answer_type": "single_select",
        "scoreable": True,
        "reverse_scored": False,
        "options": ["Restless", "Light", "Mostly restful", "Deeply restful"],
        "routing_text": "Support is available. This answer routes to your PT/IM provider for review.",
        "routing_trigger": ["Restless", "Light"],
        "provider_route": "PT/IM",
        "ai_tags": ["sleep", "baseline", "provider-review"],
    },
    {
        "id": 15,
        "code": "ob_15",
        "category": "SLEEP",
        "readiness_component": "Sleep Readiness",
        "question": "How often do you wake feeling recovered?",
        "description": "Choose the response that fits you best. Your answers build a starting baseline.",
        "answer_type": "single_select",
        "scoreable": True,
        "reverse_scored": False,
        "options": ["Never", "Sometimes", "Most mornings", "Every morning"],
        "routing_text": "Support is available. This answer routes to your PT/IM provider for review.",
        "routing_trigger": ["Never"],
        "provider_route": "PT/IM",
        "ai_tags": ["sleep", "baseline", "provider-review"],
    },
    {
        "id": 16,
        "code": "ob_16",
        "category": "PHYSICAL",
        "readiness_component": "Physical Readiness",
        "question": "Do you have any ongoing medical conditions or prescriptions we should know about?",
        "description": "This sets context for your providers. Your choice opens a short follow-up.",
        "answer_type": "single_select",
        "scoreable": False,
        "reverse_scored": False,
        "options": ["No", "Yes - minor", "Yes - moderate", "Yes - significant"],
        "routing_text": "Routes to PT/IM review. Your answer fires a PT/IM review work item. It does NOT contribute to your OPS score.",
        "routing_trigger": ["Yes - minor", "Yes - moderate", "Yes - significant"],
        "provider_route": "PT/IM",
        "follow_up": {
            "type": "severity_sheet",
            "title": "How much is it affecting you?",
            "required_when_triggered": True,
            "save_label": "Save follow-up",
            "trigger_options": ["Yes - minor", "Yes - moderate", "Yes - significant"],
            "options": [
                {"label": "Minor", "description": "I can continue normal activity."},
                {"label": "Moderate", "description": "I need an adjustment or support."},
                {"label": "Significant", "description": "It is limiting normal activity."},
            ],
        },
        "ai_tags": ["physical", "flag-only", "ptim-review"],
    },
    {
        "id": 17,
        "code": "ob_17",
        "category": "PHYSICAL",
        "readiness_component": "Physical Readiness",
        "question": "Would you like to upload any medical records or clearance documents?",
        "description": "This sets context for your providers. Your choice opens a short follow-up.",
        "answer_type": "single_select",
        "scoreable": False,
        "reverse_scored": False,
        "options": ["Yes", "Maybe later", "No"],
        "routing_text": "Context-setting question. This answer is saved to your record but does not contribute to your OPS score.",
        "routing_trigger": ["Yes"],
        "provider_route": "PT/IM",
        "follow_up": {
            "type": "toggle_sheet",
            "title": "Do you want to upload documents now?",
            "required_when_triggered": True,
            "save_label": "Save follow-up",
            "trigger_options": ["Yes"],
            "options": [
                {"label": "Yes", "description": ""},
                {"label": "Maybe later", "description": ""},
                {"label": "No", "description": ""},
            ],
        },
        "ai_tags": ["physical", "document-upload", "context-only"],
    },
    {
        "id": 18,
        "code": "ob_18",
        "category": "MENTAL",
        "readiness_component": "Mental Readiness",
        "question": "Which support pathways would you like enabled?",
        "description": "This sets context for your providers. Your choice opens a short follow-up.",
        "answer_type": "multi_select",
        "scoreable": False,
        "reverse_scored": False,
        "options": ["Nutritionist", "Mental Performance", "Chaplain", "SCS"],
        "routing_text": "Context-setting question. This answer is saved to your record but does not contribute to your OPS score.",
        "routing_trigger": ["Nutritionist", "Mental Performance", "Chaplain", "SCS"],
        "provider_route": "Support Pathways",
        "follow_up": {
            "type": "role_sheet",
            "title": "Choose your support pathways",
            "required_when_triggered": True,
            "save_label": "Save follow-up",
            "helper_text": "Select all that apply. SCS is locked on.",
            "trigger_options": ["Nutritionist", "Mental Performance", "Chaplain", "SCS"],
            "options": [
                {"label": "Nutritionist", "description": "Toggle to enable"},
                {"label": "Mental Performance", "description": "Toggle to enable"},
                {"label": "Chaplain", "description": "Toggle to enable"},
                {"label": "SCS", "description": "Required (locked on)", "disabled": True, "value": True},
            ],
        },
        "ai_tags": ["mental", "support-pathways", "context-only"],
    },
    {
        "id": 19,
        "code": "ob_19",
        "category": "SPIRITUAL",
        "readiness_component": "Spiritual Readiness",
        "question": "What is the top readiness goal you want to focus on first?",
        "description": "This sets context for your providers. Your choice opens a short follow-up.",
        "answer_type": "single_select",
        "scoreable": False,
        "reverse_scored": False,
        "options": ["Physical performance", "Mental resilience", "Nutrition & recovery", "Purpose & connection"],
        "routing_text": "Context-setting question. This answer is saved to your record but does not contribute to your OPS score.",
        "routing_trigger": ["Physical performance", "Mental resilience", "Nutrition & recovery", "Purpose & connection"],
        "provider_route": "Context Only",
        "follow_up": {
            "type": "text_sheet",
            "title": "What is your top readiness goal?",
            "required_when_triggered": True,
            "save_label": "Save follow-up",
            "trigger_options": ["Physical performance", "Mental resilience", "Nutrition & recovery", "Purpose & connection"],
            "placeholder": "Short answer (120 char max)",
            "max_length": 120,
        },
        "ai_tags": ["spiritual", "goal", "context-only"],
    },
    {
        "id": 20,
        "code": "ob_20",
        "category": "MENTAL",
        "readiness_component": "Mental Readiness",
        "question": "How often would you like Ascend to check in with you?",
        "description": "This sets context for your providers. Your choice opens a short follow-up.",
        "answer_type": "single_select",
        "scoreable": False,
        "reverse_scored": False,
        "options": ["Daily", "Weekly", "As-needed"],
        "routing_text": "Context-setting question. This answer is saved to your record but does not contribute to your OPS score.",
        "routing_trigger": ["Daily", "Weekly", "As-needed"],
        "provider_route": "Cadence Preference",
        "follow_up": {
            "type": "toggle_sheet",
            "title": "How often should Ascend check in?",
            "required_when_triggered": True,
            "save_label": "Save follow-up",
            "trigger_options": ["Daily", "Weekly", "As-needed"],
            "options": [
                {"label": "Daily", "description": ""},
                {"label": "Weekly", "description": ""},
                {"label": "As-needed", "description": ""},
            ],
        },
        "ai_tags": ["mental", "cadence-preference", "context-only"],
    },
]


def get_onboarding_question_bank() -> list[dict[str, Any]]:
    """Return the normalized onboarding question bank."""
    return ONBOARDING_QUESTION_BANK


def get_onboarding_question_by_id(question_id: int) -> dict[str, Any] | None:
    """Return a question definition by numeric id."""
    for question in ONBOARDING_QUESTION_BANK:
        if question["id"] == question_id:
            return question
    return None
