"""Personal Wellness Report schemas ("Your readiness story").

Not a DOCX-named screen - the underlying data (OPS, band, component scores,
the 70-point "worth a conversation" threshold) all reuse already
DOCX-verified logic. "Standout insights" are generated by real pattern
detection over stored `OpsSnapshot` history, never fabricated - the list is
0-3 items depending on what the data actually supports, not always 3.
"""

from typing import Any

from pydantic import BaseModel


class DriverSummaryItem(BaseModel):
    """One driver's 30-day average score."""

    readiness_component: str
    signal_label: str
    average_score: float | None


class StandoutInsight(BaseModel):
    """A single real, data-derived highlight."""

    key: str
    severity: str
    title: str
    body: str


class WellnessReportResponse(BaseModel):
    """Personal 30-day wellness report payload."""

    period_label: str
    average_ops: float | None
    average_ops_delta: float | None
    band: str
    band_narrative: str
    driver_summary: list[DriverSummaryItem]
    standout_insights: list[StandoutInsight]
    footer_note: str
